spring.application.name=task-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-calm-flower-ayw2of0p-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JEXpF4Kg9rbI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect